### ISSUE TITLE
`Rack::Protection::CookieTossing` test fail with Rack 3.1.3

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#2017]
From https://github.com/sinatra/sinatra/actions/runs/9565078027/job/26367227204

```
Failures:

  1) Rack::Protection::CookieTossing with default reaction adds the correct Set-Cookie header
     Failure/Error: expect(last_response.headers['Set-Cookie']).to eq(expected_header)

       expected: ["rack.%2573ession=; domain=example.org; path=/; expires=Thu, 01 Jan [19](https://github.com/sinatra/sinatra/actions/runs/9565078027/job/26367227204#step:4:20)70 00:00:00 GMT", "rack.%2573e...0 GMT", "rack.session=; domain=example.org; path=/some/path; expires=Thu, 01 Jan 1970 00:00:00 GMT"]
            got: ["rack.%73ession=; domain=example.org; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT", "rack.%73essio...0 GMT", "rack.session=; domain=example.org; path=/some/path; expires=Thu, 01 Jan 1970 00:00:00 GMT"]

       (compared using ==)
     # ./spec/lib/rack/protection/cookie_tossing_spec.rb:40:in `block (3 levels) in <top (required)>'
```
